#!/usr/bin/env bash

# Simple script to enable/disable external screen running on DP-2

xrandr |grep -q DP-2.*1280
if [[ $? -eq 0 ]]; then
  xrandr --output DP-2 --off
else
  xrandr --output DP-2 --auto --mode 1280x1024 --pos 1280x0
fi
