#!/usr/bin/env expect

# Authenticates to an ftp server and uploads a file
#
# usage: ./ftp.exp host filename password


set host [lrange $argv 0 0]
set filename [lrange $argv 1 1]
set password [lrange $argv 2 2]

spawn ftp $host
expect "Name ($host:root):"
send "scan\r"
expect "Password:"
send "$password\r"
expect "ftp>"
send "lcd /tmp\r"
expect "ftp>"
send "put $filename\r"
expect "ftp>"
send "bye\r"
#interact

