#!/usr/bin/perl -w

#
# check_nagios_qps - Nagios plugin
#
#
# Copyright (C) 2011 Amro Diab
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Nagios check for mysql QPS
# Report bugs to: adiab@hotmail.co.uk

use Getopt::Long;


GetOptions
        ("V"   => \$opt_V, "version"    => \$opt_V,
         "u=s"   => \$opt_u, "user"    => \$opt_u,
         "p=s"   => \$opt_p, "password"    => \$opt_p,
         "w=s" => \$opt_w, "warning=s"  => \$opt_w,
         "c=s" => \$opt_c, "critical=s" => \$opt_c,
         "H=s" => \$opt_H, "hostname=s" => \$opt_H);

die "Password required" unless defined $opt_p;
die "Hostname required" unless defined $opt_H;
die "username required" unless defined $opt_u;

die "critical required" unless defined $opt_c;
die "warning required" unless defined $opt_w;

#$var=`/usr/lib64/nagios/plugins/check_mysql -u $opt_u -p $opt_p`;
$var=`echo status | /usr/bin/mysql -h $opt_H -u $opt_u -p$opt_p|grep ^Threads`;

$var =~ s/.*avg\://;
$var =~ s/^\s+//;
#print "$var\n";

if ($var > $opt_c) {
  $output="Critical";
  $exit=2;
}

elsif ($var > $opt_w) {
  $output="Warning";
  $exit=1;
}
else {
  $output="OK";
  $exit=0;
}

print "$output QPS=$var";
exit $exit;
