<?php

	define('NAVBAR_TITLE', 'About Us');
	define('HEADING_TITLE', 'About Us');
	

	define('TEXT_LAST_UPDATED', 'last updated - ');
	

define('ABOUT_TEXT', '<h3>About Us</h3>Amrox Online is dedicated to provied the best and most diverse choise of Linux VPS solutions.  We strongly believe that everybody\'s requirements are different and therefore package deals are not suitable and simply force customers to make sacrifices on certain aspects of their requirements.  <br><br>  All of our solutions allow you to custom build, choosing from various options.  Why buy features that you do not actually need, or be forced to comprise on key features when you can have a solution customised to you unique requirements.<br><br>  We offer a wide range of Linux distributions and versions.  So whether you\re an application tester wanting to try a product on a different platform, or a Linux enthuiast we are certain we have a product suited to your needs.  <br><br>We are constantly testing out new products to offer you, so if you do not immedietly see what you require please feel free to <a href=contact_us.php>contact us</a> and let us know your requirements. ');

define('TRANSFER_TEXT', '<h3>Resume VPS Payment</h3>  Please enter transfer code and click subscribe to be forwarded to Paypal');
define('RESUME_TEXT', '<h3>Resume VPS</h3>  Please enter VPS resume code and click subscribe to be forwarded to Paypal');
define('UPGRADE_TEXT','<h3>Upgrade VPS</h3> Please Click subscribe to be forwarded to Paypal');

define('REQUEST_TEXT','<H3>Custom VPS Request</h3>2x Ubuntu 9.10 64-bit: <ul><li>Unlimited bandwidth</li><li>30GB HD</li><li>4096Mb RAM</li><li>10xIP Addresses</li><li>Reboot/reinstall support</li></ul>');

define('TRANSFER_FORM', '<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="M3YLWX3DX8RVC"><table><tr><td><input type="hidden" name="on0" value="Transfer Code">Transfer Code</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM', '<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="RSX75RX5LU9LW"><table><tr><td><input type="hidden" name="on0" value="VPS Code:">VPS Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_123','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="KVQ7MWMRM4A82"><table><tr><td><input type="hidden" name="on0" value="VPS Code:">VPS Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');
define('RESUME_FORM_127','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="MQWN7TZSMQU34"><table><tr><td><input type="hidden" name="on0" value="VPS Code:">VPS Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_143','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="AL2NFST8Q8PDL"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_141','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="BAXD46ZGHLFR8"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');
define('RESUME_FORM_157','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="LVEBVRXTH52GE"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');
define('RESUME_FORM_158','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="768HJU4HU8CZA"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');
define('RESUME_FORM_161','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="JUNA43MXHMWQW"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_106','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="MQWN7TZSMQU34"><table><tr><td><input type="hidden" name="on0" value="VPS Code:">VPS Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');
define('RESUME_FORM_113', '<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"> <input type="hidden" name="cmd" value="_s-xclick"> <input type="hidden" name="hosted_button_id" value="HR6NEKEXQHLPW"> <table> <tr><td><input type="hidden" name="on0" value="VPS Code:">VPS Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr> </table> <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online."> <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"> </form>/<center>');
define('RESUME_FORM_146','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="YNWZKJ2APE3M6"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_159','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="N4ENF26LSK4H6"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('REQUEST_FORM','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="FJ9BRMWYA25RA"><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_124','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="RASFSX942C8VQ"><table><tr><td><input type="hidden" name="on0" value="VPS 4090 2GB">VPS 4090 2GB</td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_109','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="FH7JWPBGDDYW2"><table><tr><td><input type="hidden" name="on0" value="VPS 4070 2GB">VPS 4070 2GB</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');

define('RESUME_FORM_148','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="MXF5YJ889HQSA"><table><tr><td><input type="hidden" name="on0" value="Resume Code:">Resume Code:</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');


define('RESUME_FORM_102','<center><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="XBB4VVNT2RTRU"><table><tr><td><input type="hidden" name="on0" value="VPS  1GB">VPS 4067 1GB</td></tr><tr><td><input type="text" name="os0" maxlength="200"></td></tr></table><input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online."><img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1"></form></center>');
